### ISSUE TITLE
Not able to add post from Mobile App (Android)

### ISSUE THREAD

**Issue by abhimanyu56** [shanhuiyang/TypeScript-MERN-Starter#114]
I am running expo. I am not able to add post from Mobile device... no error no log in console..
Can you help here?
Also can you tell me why there is no reading/adding functionality on mobile?
Anything quick can be done to start comment functionality?

**Comment by shanhuiyang** [comment]
Hi @abhimanyu56 thanks for your feedback.
I think there is the functionality to add post, please check that you have changed the `HostUrl` to your LAN IP as indicated in the readme.
There is no comment functionality yet since the feature progress on mobile is behind the website. I am planning on the jobs in the rest of this year which should including comments. Meanwhile you are welcome to contribute to this.
